// Shape type metadata (CLEANUP S2 slice 6) — two pure data maps shared by the properties facade, the
// per-type renderers, the convert helpers, and autoSizeCell. Zero deps; no facade import. TYPE_LABELS =
// human-readable type names; DEFAULT_SIZES = the per-type fallback size for "Auto Size" / conversions.

// Human-readable display names for shape types
export const TYPE_LABELS = {
  'sf.SimpleNode':     'Node',
  'sf.Container':      'Container',
  'sf.TextLabel':      'Text',
  'sf.Note':           'Note',
  'sf.Image':          'Image',
  'sf.Task':           'Task',
  'sf.TaskGroup':      'Task Group',
  'sf.Zone':           'Zone',
  'sf.BpmnEvent':      'Event',
  'sf.BpmnTask':       'Task',
  'sf.BpmnGateway':    'Gateway',
  'sf.BpmnSubprocess': 'Subprocess',
  'sf.BpmnLoop':       'Loop',
  'sf.BpmnPool':       'Pool',
  'sf.BpmnDataObject': 'Data Object',
  'sf.FlowProcess':    'Process',
  'sf.FlowDecision':   'Decision',
  'sf.FlowTerminator': 'Terminator',
  'sf.FlowDatabase':   'Database',
  'sf.FlowDocument':   'Document',
  'sf.FlowIO':         'Input / Output',
  'sf.FlowPredefined': 'Predefined Process',
  'sf.FlowOffPage':    'Off-Page Link',
  'sf.Annotation':     'Annotation',
  'sf.Line':           'Line',
  'sf.Link':           'Link',
  'sf.DataObject':     'Object',
  'sf.OrgPerson':      'Person',
  'sf.GanttTask':      'Task',
  'sf.GanttMilestone': 'Milestone',
  'sf.GanttMarker':    'Day Marker',
  'sf.GanttTimeline':  'Timeline',
  'sf.GanttGroup':     'Group',
  'sf.SequenceParticipant': 'Participant',
  'sf.SequenceActor':       'Actor',
  'sf.SequenceActivation':  'Activation',
  'sf.SequenceFragment':    'Fragment',
  'df.Pill':                'Pill',
  'df.Legend':              'Legend',
  'df.Table':               'Table',
};

// Default sizes used by "Auto Size"
export const DEFAULT_SIZES = {
  'sf.SimpleNode':     { width: 180, height: 64 },
  'sf.Container':      { width: 360, height: 240 },
  'sf.Zone':           { width: 400, height: 300 },
  'sf.TaskGroup':      { width: 640, height: 360 },
  'sf.TextLabel':      { width: 200, height: 32 },
  'sf.Note':           { width: 200, height: 120 },
  'sf.Image':          { width: 240, height: 180 },
  'sf.Task':           { width: 540, height: 160 },
  'sf.BpmnEvent':      { width: 40,  height: 40 },
  'sf.BpmnTask':       { width: 120, height: 60 },
  'sf.BpmnGateway':    { width: 48,  height: 48 },
  'sf.BpmnSubprocess': { width: 360, height: 240 },
  'sf.BpmnLoop':       { width: 360, height: 240 },
  'sf.BpmnPool':       { width: 600, height: 250 },
  'sf.BpmnDataObject': { width: 40,  height: 50 },
  'sf.FlowProcess':    { width: 120, height: 60 },
  'sf.FlowDecision':   { width: 120, height: 80 },
  'sf.FlowTerminator': { width: 120, height: 60 },
  'sf.FlowDatabase':   { width: 80,  height: 60 },
  'sf.FlowDocument':   { width: 120, height: 60 },
  'sf.FlowIO':         { width: 140, height: 60 },
  'sf.FlowPredefined': { width: 120, height: 60 },
  'sf.FlowOffPage':    { width: 60,  height: 60 },
  'sf.Annotation':     { width: 100, height: 120 },
  'sf.Line':           { width: 200, height: 8 },
  'df.Pill':           { width: 32,  height: 32 },
  'df.Legend':         { width: 120, height: 28 },
  'df.Table':          { width: 330, height: 90 },
  'sf.Link':           { width: 220, height: 44 },
  'sf.DataObject':     { width: 260, height: 80 },
  'sf.GanttTask':      { width: 240, height: 32 },
  'sf.GanttMilestone': { width: 24,  height: 24 },
  'sf.GanttMarker':    { width: 20,  height: 16 },
  'sf.GanttTimeline':  { width: 960, height: 48 },
  'sf.GanttGroup':     { width: 360, height: 24 },
  'sf.OrgPerson':      { width: 280, height: 90 },
  'sf.SequenceParticipant': { width: 140, height: 360 },
  'sf.SequenceActor':       { width: 100, height: 340 },
  'sf.SequenceActivation':  { width: 12,  height: 80 },
  'sf.SequenceFragment':    { width: 400, height: 200 },
};
